#!/usr/bin/env bash
set -euo pipefail

# ─── Air Install IPA — First-run setup ──────────────────────────────────────
# Guides the user through choosing a deploy mode and configuring it.
# Stores config in ~/.config/air-install-ipa/config for future deploys.
#
# Non-interactive mode (for CI/agent use):
#   setup.sh --mode local --hostname NAME
#   setup.sh --mode cloud [--bucket NAME] [--pages NAME] [--url URL]

CONFIG_DIR="$HOME/.config/air-install-ipa"
CONFIG_FILE="$CONFIG_DIR/config"

fail() { echo "Error: $1" >&2; exit 1; }
log()  { echo "▸ $*" >&2; }
ok()   { echo "✓ $*" >&2; }

# ─── Parse args ─────────────────────────────────────────────────────────────
ARG_MODE=""
ARG_HOSTNAME=""
ARG_BUCKET=""
ARG_PAGES=""
ARG_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)     ARG_MODE="$2";     shift 2 ;;
    --hostname) ARG_HOSTNAME="$2"; shift 2 ;;
    --bucket)   ARG_BUCKET="$2";   shift 2 ;;
    --pages)    ARG_PAGES="$2";    shift 2 ;;
    --url)      ARG_URL="$2";      shift 2 ;;
    -h|--help)
      echo "Usage: setup.sh --mode local|cloud [--hostname NAME] [--bucket NAME] [--pages NAME] [--url URL]"
      exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Detect if stdin is a terminal (interactive) or pipe/agent (non-interactive)
INTERACTIVE=false
[[ -t 0 ]] && INTERACTIVE=true

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║        Air Install IPA — Setup               ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Step 1: Choose deploy mode ──────────────────────────────────────────
if [[ -n "$ARG_MODE" ]]; then
  DEPLOY_MODE="$ARG_MODE"
else
  echo "Choose your deploy mode:"
  echo ""
  echo "  [1] Local HTTPS (recommended)"
  echo "      Serves IPA from this Mac over the local network."
  echo "      ✓ Fastest — no upload, instant deploy"
  echo "      ✓ Works offline"
  echo "      ✗ iPhone must be on the same network as this Mac"
  echo "      ✗ First-time: iPhone must trust a CA certificate (one-time setup)"
  echo "      Requires: mkcert, python3"
  echo ""
  echo "  [2] Cloud (Cloudflare R2 + Pages)"
  echo "      Uploads IPA to Cloudflare, generates a public install URL."
  echo "      ✓ Works from anywhere — no local network needed"
  echo "      ✓ No certificate trust needed on iPhone"
  echo "      ✗ Requires Cloudflare account (free tier works)"
  echo "      ✗ Slower — uploads IPA each time"
  echo "      Requires: wrangler CLI"
  echo ""

  if [[ "$INTERACTIVE" == "true" ]]; then
    read -r -p "  Enter 1 or 2: " MODE_INPUT
    case "$MODE_INPUT" in
      1) DEPLOY_MODE="local" ;;
      2) DEPLOY_MODE="cloud" ;;
      *) fail "Invalid choice. Enter 1 or 2." ;;
    esac
  else
    fail "No --mode specified. Use: setup.sh --mode local|cloud"
  fi
fi

case "$DEPLOY_MODE" in
  local|cloud) ;;
  *) fail "Invalid mode '$DEPLOY_MODE'. Must be 'local' or 'cloud'." ;;
esac

ok "Deploy mode: $DEPLOY_MODE"
echo ""

# ─── Local mode setup ────────────────────────────────────────────────────
if [[ "$DEPLOY_MODE" == "local" ]]; then
  echo "─── Local HTTPS setup ───"
  echo ""

  # Hostname
  DEFAULT_HOSTNAME="localhost"
  if [[ -n "$ARG_HOSTNAME" ]]; then
    LOCAL_HOSTNAME="$ARG_HOSTNAME"
  elif [[ "$INTERACTIVE" == "true" ]]; then
    echo "  Enter the local hostname for your Mac (e.g. my-mac.local)."
    echo "  Your iPhone will use this to connect: https://HOSTNAME:PORT"
    read -r -p "  Hostname [$DEFAULT_HOSTNAME]: " HOSTNAME_INPUT
    LOCAL_HOSTNAME="${HOSTNAME_INPUT:-$DEFAULT_HOSTNAME}"
  else
    LOCAL_HOSTNAME="$DEFAULT_HOSTNAME"
  fi
  ok "Hostname: $LOCAL_HOSTNAME"
  echo ""

  # Check/install mkcert
  if ! command -v mkcert >/dev/null 2>&1; then
    echo "  mkcert is required but not installed."
    echo "  Install with: brew install mkcert && mkcert -install"
    fail "mkcert not found"
  fi

  # Generate certs if not present
  CERT_DIR="$CONFIG_DIR/certs"
  CERT_FILE="$(find "$CERT_DIR" -name "${LOCAL_HOSTNAME}*.pem" ! -name "*-key.pem" 2>/dev/null | head -1 || true)"
  KEY_FILE="$(find "$CERT_DIR" -name "${LOCAL_HOSTNAME}*-key.pem" 2>/dev/null | head -1 || true)"

  if [[ -z "$CERT_FILE" || -z "$KEY_FILE" ]]; then
    log "Generating mkcert certificates for $LOCAL_HOSTNAME..."
    mkdir -p "$CERT_DIR"
    (cd "$CERT_DIR" && mkcert "$LOCAL_HOSTNAME" localhost 127.0.0.1)
    ok "Certificates generated in $CERT_DIR"
  else
    ok "Certificates already exist for $LOCAL_HOSTNAME"
  fi
  echo ""

  # Save config
  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# Air Install IPA — config
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DEPLOY_MODE=local
LOCAL_HOSTNAME=$LOCAL_HOSTNAME
EOF

# ─── Cloud mode setup ────────────────────────────────────────────────────
elif [[ "$DEPLOY_MODE" == "cloud" ]]; then
  echo "─── Cloud (Cloudflare) setup ───"
  echo ""

  command -v wrangler >/dev/null 2>&1 || fail "wrangler not found. Install: npm i -g wrangler"

  # Wrangler login
  WHOAMI_OUTPUT="$(wrangler whoami 2>&1 || true)"
  if echo "$WHOAMI_OUTPUT" | grep -qE "You are logged in|Token Permissions"; then
    ACCOUNT_INFO="$(echo "$WHOAMI_OUTPUT" | grep -E '^\|' | head -2 | tail -1 || echo "")"
    ok "Already authenticated with Cloudflare. ${ACCOUNT_INFO}"
  elif [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
    if wrangler r2 bucket list >/dev/null 2>&1; then
      ok "Authenticated via CLOUDFLARE_API_TOKEN."
    else
      fail "CLOUDFLARE_API_TOKEN is set but appears invalid. Check that the token has the required permissions (see below)."
    fi
  else
    if [[ "$INTERACTIVE" == "true" ]]; then
      log "Opening browser for Cloudflare login..."
      wrangler login
      if ! wrangler whoami 2>&1 | grep -qE "You are logged in|Token Permissions"; then
        fail "Login failed. Run 'wrangler login' manually and try again."
      fi
      ok "Logged in to Cloudflare."
    else
      echo ""
      echo "  Cloudflare authentication required."
      echo ""
      echo "  Option A: Run 'wrangler login' in your terminal (opens browser)."
      echo ""
      echo "  Option B: Create an API token and set it as an environment variable:"
      echo ""
      echo "    1. Go to: https://dash.cloudflare.com/profile/api-tokens"
      echo "    2. Click 'Create Token'"
      echo "    3. Select 'Create Custom Token' at the bottom"
      echo "    4. Configure the token with these permissions:"
      echo "       - Account | Cloudflare Pages | Edit"
      echo "       - Account | Workers R2 Storage  | Edit"
      echo "    5. (Optional) Restrict to your specific account under 'Account Resources'"
      echo "    6. Click 'Continue to summary' → 'Create Token'"
      echo "    7. Copy the token value"
      echo ""
      echo "  Then set it in your shell profile (~/.zshrc or ~/.bashrc):"
      echo ""
      echo "    export CLOUDFLARE_API_TOKEN=\"your-token-here\""
      echo ""
      echo "  Or pass it inline:"
      echo ""
      echo "    CLOUDFLARE_API_TOKEN=\"your-token\" bash ~/.claude/skills/air-install-ipa/scripts/setup.sh --mode cloud"
      echo ""
      fail "Not authenticated. Follow the instructions above to set up Cloudflare access."
    fi
  fi
  echo ""

  # R2 bucket
  DEFAULT_BUCKET="ipa-ota-install"
  if [[ -n "$ARG_BUCKET" ]]; then
    R2_BUCKET="$ARG_BUCKET"
  elif [[ "$INTERACTIVE" == "true" ]]; then
    read -r -p "  R2 bucket name [$DEFAULT_BUCKET]: " BUCKET_INPUT
    R2_BUCKET="${BUCKET_INPUT:-$DEFAULT_BUCKET}"
  else
    R2_BUCKET="$DEFAULT_BUCKET"
  fi

  BUCKET_LIST="$(wrangler r2 bucket list 2>&1)"
  if echo "$BUCKET_LIST" | grep -q "$R2_BUCKET"; then
    ok "Bucket '$R2_BUCKET' already exists."
  else
    log "Creating R2 bucket '$R2_BUCKET'..."
    wrangler r2 bucket create "$R2_BUCKET"
    ok "Bucket '$R2_BUCKET' created."
  fi
  echo ""

  # R2 public URL
  if [[ -n "$ARG_URL" ]]; then
    R2_PUBLIC_URL="$ARG_URL"
  else
    log "Enabling dev URL for bucket '$R2_BUCKET'..."
    wrangler r2 bucket dev-url enable "$R2_BUCKET" 2>/dev/null || true
    R2_PUBLIC_URL="$(wrangler r2 bucket dev-url get "$R2_BUCKET" 2>&1 | grep -oE 'https://[a-zA-Z0-9._-]+\.r2\.dev' | head -1 || echo "")"
    if [[ -z "$R2_PUBLIC_URL" ]]; then
      if [[ "$INTERACTIVE" == "true" ]]; then
        echo "  Could not auto-detect the R2 public URL."
        read -r -p "  Paste the public URL here: " R2_PUBLIC_URL
        [[ -n "$R2_PUBLIC_URL" ]] || fail "R2 public URL is required."
      else
        fail "Could not auto-detect R2 public URL. Pass --url."
      fi
    fi
  fi
  ok "R2 public URL: $R2_PUBLIC_URL"
  echo ""

  # Pages project
  DEFAULT_PAGES="ipa-ota-install"
  if [[ -n "$ARG_PAGES" ]]; then
    PAGES_PROJECT="$ARG_PAGES"
  elif [[ "$INTERACTIVE" == "true" ]]; then
    read -r -p "  Pages project name [$DEFAULT_PAGES]: " PAGES_INPUT
    PAGES_PROJECT="${PAGES_INPUT:-$DEFAULT_PAGES}"
  else
    PAGES_PROJECT="$DEFAULT_PAGES"
  fi
  ok "Pages project: $PAGES_PROJECT"
  echo ""

  # Save config
  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# Air Install IPA — config
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DEPLOY_MODE=cloud
R2_BUCKET=$R2_BUCKET
R2_PUBLIC_URL=$R2_PUBLIC_URL
PAGES_PROJECT=$PAGES_PROJECT
EOF
fi

chmod 600 "$CONFIG_FILE"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "Setup complete! Config saved to: $CONFIG_FILE"
echo ""
echo "  Deploy mode: $DEPLOY_MODE"
echo "  You can now deploy with:"
echo "    /air-install-ipa"
echo "    /air-install-ipa path/to/App.ipa"
echo ""
echo "  To reconfigure, run this setup again."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
